color: null
fieldLayouts:
  b20620a5-d578-4c78-998e-705918673889:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T17:37:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c89b093b-b78f-40d5-a56e-3c87539ff489
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T17:39:01+00:00'
            elementCondition: null
            fieldUid: da714b55-a04c-4269-85fd-7ab743a0bf2b # Switch
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c11b749-28b5-4aec-bb90-85031716810f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T17:39:01+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: da714b55-a04c-4269-85fd-7ab743a0bf2b # Switch
                  layoutElementUid: 2c11b749-28b5-4aec-bb90-85031716810f
                  uid: ad507292-f948-4480-bf6e-0542ed53d336
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4528f321-cffc-46ae-b89a-8b6956271988 # Text OFF
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e571706a-c7ac-4419-b935-b7148454c8f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T17:39:01+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: da714b55-a04c-4269-85fd-7ab743a0bf2b # Switch
                  layoutElementUid: 2c11b749-28b5-4aec-bb90-85031716810f
                  uid: 7294f5c0-1ec7-4c77-8795-f1131ac35fac
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: adc0d524-01bd-4bb3-8f35-ba91943efb90 # Text ON
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec2e6634-a421-41f8-a7ec-82dec4cb7f13
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5fcbd4fd-8424-414d-abfe-9506d060e045
        userCondition: null
handle: condtional
hasTitleField: true
icon: ''
name: Condtional
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
