color: null
fieldLayouts:
  7e96a501-803e-4677-b1d0-b31de1a32bb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T17:30:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd7e8f86-0938-4f6a-a84c-6bf2a617f4d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T17:38:00+00:00'
            elementCondition: null
            fieldUid: e6df5007-e040-4014-b74c-6addcb50730a # Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e8b1505-ded4-4d74-a21f-79ebb195b524
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c09b3a2-901b-451a-9628-0cbc3719184e
        userCondition: null
handle: default
hasTitleField: true
icon: ''
name: Default
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
