color: null
fieldLayouts:
  b2bff3e5-12ee-4726-a791-25ede9062c3b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T17:36:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 538ab32d-4776-43c9-b5b1-307223dbccb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T17:37:31+00:00'
            elementCondition: null
            fieldUid: adc0d524-01bd-4bb3-8f35-ba91943efb90 # Text ON
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebf00a1-282f-4396-94c8-ee67edeb306d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbd20e82-4895-4185-a26c-d5f8b9d5939a
        userCondition: null
handle: textonly
hasTitleField: true
icon: ''
name: 'Text only'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
